apiVersion: batch/v1
kind: Job
metadata:
  name: centos7-job
  labels:
    app: centos7-app
spec:
  template:
    metadata:
      labels:
        app: centos7-app
    spec:
      containers:
        - name: centos7-container
          image: localhost:5000/centos7-app:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "/app/start.sh"]
          volumeMounts:
            - name: host-volume
              mountPath: /hostPath
      restartPolicy: Never
      volumes:
        - name: host-volume
          hostPath:
            path: /hostPath
  backoffLimit: 4
